Repository samuel-gomez/react-starter-toolkit, pull requests merged in 2022-12, with the labels that each got.

#355 fix(clean): self deleted script for windows
  package.json
  src/pages/Demos/DateInput/__tests__/DateInput.test.tsx
  src/pages/Demos/DateInput/__tests__/__snapshots__/DateInput.test.tsx.snap
  src/shared/components/Editor/InputEditor/__tests__/__snapshots__/InputEditor.test.tsx.snap
Labels: bug

#358 fix(sonar): fix sonar rules
  package-lock.json
  public/environment.development.json
  public/environment.production.local.json
  src/App/FetchProvider/FetchProvider.tsx
  src/shared/components/LiveCode/Accessibility/AccordionResults/AccordionResults.tsx
  src/shared/components/LiveCode/Accessibility/AccordionResults/__tests__/AccordionResults.test.tsx
  src/shared/components/LiveCode/Accessibility/AccordionResults/__tests__/__snapshots__/AccordionResults.test.tsx.snap
  src/shared/components/LiveCode/Accessibility/__tests__/Accessibility.container.test.tsx
  src/shared/components/LiveCode/Accessibility/__tests__/Accessibility.test.tsx
  src/shared/components/LiveCode/Accessibility/__tests__/__snapshots__/Accessibility.container.test.tsx.snap
  src/shared/components/LiveCode/Accessibility/__tests__/__snapshots__/Accessibility.test.tsx.snap
  src/shared/components/LiveCode/LiveCode.tsx
  src/shared/components/LiveCode/ReadMe/ReadMe.tsx
  src/shared/components/LiveCode/TabsLiveCode/TabsLiveCode.tsx
Labels: documentation, refactor

#359 fix(restitution): fix values of restitution
  package.json
  src/App/__tests__/__snapshots__/App.test.tsx.snap
  src/Layout/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/pages/Demos/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
  src/pages/Demos/Action/__tests__/__snapshots__/Action.test.tsx.snap
  src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
  src/pages/Demos/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
  src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
  src/pages/Demos/CheckboxInput/__tests__/__snapshots__/CheckboxInput.test.tsx.snap
  src/pages/Demos/DateInput/__tests__/__snapshots__/DateInput.test.tsx.snap
  src/pages/Demos/FileInput/__tests__/__snapshots__/FileInput.test.tsx.snap
  src/pages/Demos/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/pages/Demos/FooterClient/__tests__/__snapshots__/FooterClient.test.tsx.snap
  src/pages/Demos/Header/__tests__/__snapshots__/Header.test.tsx.snap
  src/pages/Demos/Help/__tests__/__snapshots__/Help.test.tsx.snap
  src/pages/Demos/Infos/__tests__/__snapshots__/Infos.test.tsx.snap
  src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/pages/Demos/Loader/__tests__/__snapshots__/Loader.test.tsx.snap
  src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/pages/Demos/ModalCustom/__tests__/__snapshots__/ModalCustom.container.test.tsx.snap
  src/pages/Demos/ModalCustom/__tests__/__snapshots__/ModalCustom.test.tsx.snap
  src/pages/Demos/NavBar/__tests__/__snapshots__/NavBar.test.tsx.snap
  src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
  src/pages/Demos/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
  src/pages/Demos/RadioInput/__tests__/__snapshots__/RadioInput.test.tsx.snap
  src/pages/Demos/Restitution/Restitution.tsx
  src/pages/Demos/Restitution/__tests__/Restitution.test.tsx
  src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
  src/pages/Demos/SearchMembers/__tests__/__snapshots__/SearchMembers.test.tsx.snap
  src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
  src/pages/Demos/SelectMulti/__tests__/__snapshots__/SelectMulti.test.tsx.snap
  src/pages/Demos/Slider/__tests__/__snapshots__/Slider.test.tsx.snap
  src/pages/Demos/Stepper/__tests__/__snapshots__/Stepper.test.tsx.snap
  src/pages/Demos/Switch/__tests__/__snapshots__/Switch.test.tsx.snap
  src/pages/Demos/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  src/pages/Demos/TextareaInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  src/pages/Demos/Title/__tests__/__snapshots__/Title.test.tsx.snap
  src/pages/Demos/TitleBar/__tests__/__snapshots__/TitleBar.test.tsx.snap
Labels: bug

#360 fix(clean): update constants
  package-lock.json
  package.json
  scripts/clean.js
  scripts/files/public/environment.development.json
  scripts/files/src/shared/constants.ts
  scripts/files/src/shared/testsUtils/constants.ts
  scripts/files/src/shared/testsUtils/msw.ts
  src/App/__tests__/__snapshots__/App.test.tsx.snap
  src/Layout/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/pages/Demos/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
  src/pages/Demos/Action/__tests__/__snapshots__/Action.test.tsx.snap
  src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
  src/pages/Demos/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
  src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
  src/pages/Demos/CheckboxInput/__tests__/__snapshots__/CheckboxInput.test.tsx.snap
  src/pages/Demos/DateInput/DateInput.tsx
  src/pages/Demos/DateInput/__tests__/DateInput.test.tsx
  src/pages/Demos/DateInput/__tests__/__snapshots__/DateInput.test.tsx.snap
  src/pages/Demos/FileInput/__tests__/__snapshots__/FileInput.test.tsx.snap
  src/pages/Demos/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/pages/Demos/FooterClient/__tests__/__snapshots__/FooterClient.test.tsx.snap
  src/pages/Demos/Header/__tests__/__snapshots__/Header.test.tsx.snap
  src/pages/Demos/Help/__tests__/__snapshots__/Help.test.tsx.snap
  src/pages/Demos/Infos/__tests__/__snapshots__/Infos.test.tsx.snap
  src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/pages/Demos/Loader/__tests__/__snapshots__/Loader.test.tsx.snap
  src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/pages/Demos/ModalCustom/__tests__/__snapshots__/ModalCustom.container.test.tsx.snap
  src/pages/Demos/ModalCustom/__tests__/__snapshots__/ModalCustom.test.tsx.snap
  src/pages/Demos/NavBar/__tests__/__snapshots__/NavBar.test.tsx.snap
  src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
  src/pages/Demos/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
  src/pages/Demos/RadioInput/__tests__/__snapshots__/RadioInput.test.tsx.snap
  src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
  src/pages/Demos/SearchMembers/__tests__/__snapshots__/SearchMembers.test.tsx.snap
  src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
  src/pages/Demos/SelectMulti/__tests__/__snapshots__/SelectMulti.test.tsx.snap
  src/pages/Demos/Slider/__tests__/__snapshots__/Slider.test.tsx.snap
  src/pages/Demos/Stepper/__tests__/__snapshots__/Stepper.test.tsx.snap
  src/pages/Demos/Switch/__tests__/__snapshots__/Switch.test.tsx.snap
  src/pages/Demos/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  src/pages/Demos/TextareaInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  src/pages/Demos/Title/__tests__/__snapshots__/Title.test.tsx.snap
  src/pages/Demos/TitleBar/__tests__/__snapshots__/TitleBar.test.tsx.snap
Labels: bug, documentation

#361 Chore/deps clean packages
  features/Home/Home.feature
  package-lock.json
  package.json
  src/App/__tests__/__snapshots__/App.test.tsx.snap
  src/Layout/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/pages/Demos/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
  src/pages/Demos/Action/__tests__/__snapshots__/Action.test.tsx.snap
  src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
  src/pages/Demos/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
  src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
  src/pages/Demos/CheckboxInput/__tests__/__snapshots__/CheckboxInput.test.tsx.snap
  src/pages/Demos/DateInput/__tests__/__snapshots__/DateInput.test.tsx.snap
  src/pages/Demos/FileInput/__tests__/__snapshots__/FileInput.test.tsx.snap
  src/pages/Demos/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/pages/Demos/FooterClient/__tests__/__snapshots__/FooterClient.test.tsx.snap
  src/pages/Demos/Header/__tests__/__snapshots__/Header.test.tsx.snap
  src/pages/Demos/Help/__tests__/__snapshots__/Help.test.tsx.snap
  src/pages/Demos/Infos/__tests__/__snapshots__/Infos.test.tsx.snap
  src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/pages/Demos/Loader/__tests__/__snapshots__/Loader.test.tsx.snap
  src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/pages/Demos/ModalCustom/__tests__/__snapshots__/ModalCustom.container.test.tsx.snap
  src/pages/Demos/ModalCustom/__tests__/__snapshots__/ModalCustom.test.tsx.snap
  src/pages/Demos/NavBar/__tests__/__snapshots__/NavBar.test.tsx.snap
  src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
  src/pages/Demos/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
  src/pages/Demos/RadioInput/__tests__/__snapshots__/RadioInput.test.tsx.snap
  src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
  src/pages/Demos/SearchMembers/__tests__/__snapshots__/SearchMembers.test.tsx.snap
  src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
  src/pages/Demos/SelectMulti/__tests__/__snapshots__/SelectMulti.test.tsx.snap
  src/pages/Demos/Slider/__tests__/__snapshots__/Slider.test.tsx.snap
  src/pages/Demos/Stepper/__tests__/__snapshots__/Stepper.test.tsx.snap
  src/pages/Demos/Switch/__tests__/__snapshots__/Switch.test.tsx.snap
  src/pages/Demos/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  src/pages/Demos/TextareaInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  src/pages/Demos/Title/__tests__/__snapshots__/Title.test.tsx.snap
  src/pages/Demos/TitleBar/__tests__/__snapshots__/TitleBar.test.tsx.snap
  src/pages/Home/Galleries/galleries.json
Labels: dependencies

#362 feat(cleaner): update package.json file
  scripts/files/package.json
Labels: dependencies
