Repository samuel-gomez/react-starter-toolkit, pull requests merged in 2022-11, with the labels that each got.

#314 chore(deps): update dependancies
  package-lock.json
  package.json
Labels: dependencies

#316 chore(deps): update dependancies
  package-lock.json
  package.json
Labels: dependencies

#338 feat(modal): add modal playground
  package-lock.json
  src/App/Routes/Routes.tsx
  src/App/Routes/constants.ts
  src/App/__tests__/__snapshots__/App.test.tsx.snap
  src/Layout/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
  src/Layout/Menu/constants.ts
  src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/pages/Demos/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
  src/pages/Demos/Action/__tests__/__snapshots__/Action.test.tsx.snap
  src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
  src/pages/Demos/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
  src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
  src/pages/Demos/CheckboxInput/__tests__/__snapshots__/CheckboxInput.test.tsx.snap
  src/pages/Demos/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/pages/Demos/FooterClient/__tests__/__snapshots__/FooterClient.test.tsx.snap
  src/pages/Demos/Header/__tests__/__snapshots__/Header.test.tsx.snap
  src/pages/Demos/Help/__tests__/__snapshots__/Help.test.tsx.snap
  src/pages/Demos/Infos/__tests__/__snapshots__/Infos.test.tsx.snap
  src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
  src/pages/Demos/Loader/__tests__/__snapshots__/Loader.test.tsx.snap
  src/pages/Demos/Members/__tests__/__snapshots__/Members.test.tsx.snap
  src/pages/Demos/Modal/Modal.tsx
  src/pages/Demos/Modal/__tests__/Modal.test.tsx
  src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/pages/Demos/Modal/constants.ts
  src/pages/Demos/Modal/index.ts
  src/pages/Demos/Modal/knobs.json
  src/pages/Demos/ModalCustom/ModalConfirm/ModalConfirm.tsx
  src/pages/Demos/ModalCustom/ModalConfirm/__tests__/ModalConfirm.test.tsx
  src/pages/Demos/ModalCustom/ModalConfirm/__tests__/__snapshots__/ModalConfirm.test.tsx.snap
  src/pages/Demos/ModalCustom/ModalConfirm/index.ts
  src/pages/Demos/ModalCustom/ModalCustom.container.tsx
  src/pages/Demos/ModalCustom/ModalCustom.tsx
  src/pages/Demos/ModalCustom/__tests__/ModalCustom.container.test.tsx
  src/pages/Demos/ModalCustom/__tests__/ModalCustom.test.tsx
  src/pages/Demos/ModalCustom/__tests__/__snapshots__/ModalCustom.container.test.tsx.snap
  src/pages/Demos/ModalCustom/__tests__/__snapshots__/ModalCustom.test.tsx.snap
  src/pages/Demos/ModalCustom/constants.ts
  src/pages/Demos/ModalCustom/index.ts
  src/pages/Demos/NavBar/__tests__/__snapshots__/NavBar.test.tsx.snap
  src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
  src/pages/Demos/Popover/__tests__/__snapshots__/Popover.test.tsx.snap
  src/pages/Demos/RadioInput/__tests__/__snapshots__/RadioInput.test.tsx.snap
  src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
  src/pages/Demos/SearchMembers/__tests/__snapshots__/SearchMembers.test.tsx.snap
  src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
  src/pages/Demos/Slider/__tests__/__snapshots__/Slider.test.tsx.snap
  src/pages/Demos/Stepper/__tests__/__snapshots__/Stepper.test.tsx.snap
  src/pages/Demos/Switch/__tests__/__snapshots__/Switch.test.tsx.snap
  src/pages/Demos/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  src/pages/Demos/TextareaInput/__tests__/__snapshots__/TextInput.test.tsx.snap
  src/pages/Demos/Title/__tests__/__snapshots__/Title.test.tsx.snap
  src/pages/Demos/TitleBar/__tests__/__snapshots__/TitleBar.test.tsx.snap
  src/pages/Home/__tests__/__snapshots__/Home.test.tsx.snap
  src/shared/components/Editor/Editor.tsx
Labels: enhancement, dependencies

#340 fix(searchform): fix forwardRef in search form
  src/pages/Demos/SearchMembers/SearchForm/SearchForm.tsx
Labels: bug
