Repository samuel-gomez/react-starter-toolkit, pull requests merged in 2023-03, with the labels that each got.

#399 fix(environment): fix environment apiUrl from scritps
  scripts/files/public/environment.development.json
Labels: bug

#396 refactor(table): update table custom with table toolkit
  src/Layout/Layout.scss
  src/Layout/Layout.tsx
  src/pages/Demos/ModalCustom/ModalConfirm/ModalConfirm.tsx
  src/pages/Demos/Table/Table.tsx
  src/shared/components/LiveCode/LiveCode.tsx
  src/shared/components/Table/Body/Body.tsx
  src/shared/components/Table/Body/Line/Line.container.tsx
  src/shared/components/Table/Body/Line/Line.tsx
  src/shared/components/Table/Body/Line/Td/Td.container.tsx
  src/shared/components/Table/Body/Line/Td/Td.tsx
  src/shared/components/Table/Body/Line/Td/__tests__/Td.container.test.tsx
  src/shared/components/Table/Body/Line/Td/__tests__/Td.test.tsx
  src/shared/components/Table/Body/Line/Td/__tests__/__snapshots__/Td.container.test.tsx.snap
  src/shared/components/Table/Body/Line/Td/__tests__/__snapshots__/Td.test.tsx.snap
  src/shared/components/Table/Body/Line/Td/index.ts
  src/shared/components/Table/Body/Line/__tests__/Line.container.test.tsx
  src/shared/components/Table/Body/Line/__tests__/Line.test.tsx
  src/shared/components/Table/Body/Line/__tests__/__snapshots__/Line.test.tsx.snap
  src/shared/components/Table/Header/Header.tsx
  src/shared/components/Table/Header/Th/Th.container.tsx
  src/shared/components/Table/Header/Th/Th.tsx
  src/shared/components/Table/Header/Th/ThSortable/SortingIcon.tsx
  src/shared/components/Table/Header/Th/ThSortable/ThSortable.tsx
  src/shared/components/Table/Header/Th/ThSortable/__tests__/SortingIcon.test.tsx
  src/shared/components/Table/Header/Th/ThSortable/__tests__/ThSortable.test.tsx
  src/shared/components/Table/Header/Th/ThSortable/__tests__/__snapshots__/SortingIcon.test.tsx.snap
  src/shared/components/Table/Header/Th/ThSortable/__tests__/__snapshots__/ThSortable.test.tsx.snap
  src/shared/components/Table/Header/Th/__tests__/Th.container.test.tsx
  src/shared/components/Table/Header/Th/__tests__/Th.test.tsx
  src/shared/components/Table/Header/Th/__tests__/__snapshots__/Th.test.tsx.snap
  src/shared/components/Table/Header/Th/index.ts
  src/shared/components/Table/Table.container.tsx
  src/shared/components/Table/Table.scss
  src/shared/components/Table/Table.tsx
  src/shared/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/shared/hoc/WithClassNameModifier.tsx
  src/shared/scss/custom.scss
Labels: refactor

#401 Chore/update deps
  package-lock.json
  package.json
  scripts/files/package.json
  src/App/__tests__/App.test.tsx
  src/Layout/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
  src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
Labels: documentation, dependencies
